// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi

// AwsLogRetentionInput defines model for AwsLogRetentionInput.
type AwsLogRetentionInput struct {
	RetentionInDays *int32 `json:"retentionInDays,omitempty"`
}

// AwsLogRetentionOutput defines model for AwsLogRetentionOutput.
type AwsLogRetentionOutput struct {
	Messages []Message `json:"messages"`
}

// Message defines model for Message.
type Message struct {
	Arn           string `json:"arn"`
	Message       string `json:"message"`
	NewValue      int32  `json:"newValue"`
	PreviousValue int32  `json:"previousValue"`
}

// LogGroupRetentionJSONRequestBody defines body for LogGroupRetention for application/json ContentType.
type LogGroupRetentionJSONRequestBody = AwsLogRetentionInput
