// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/2xSUWsbMQz+K0Yb7OV2viUtFL+tHYxC9tIxVhhjuD7l4uBYnqxLl4X778O+kW4kb7Kk",
	"z/q+TzqCo12iiFEymCNkt8GdreH757yi4QEFo3iK9zGNUvKJKSGLx9rFL/UP9lBTPa7tGATMu5uugTXx",
	"zgoY8FGWC2hADgnnJw7IME2nFD1t0QlMJeXjmubPsmOfygQw4AKN/VsX0EbkN1lt6Un5rPbIB5X9LgVs",
	"1b2UlJCqbcrGXlESv/O/UVW8Ysw0ssPcFjpeQhl+V0t389fQwB45z0O7tmuvYWqAEkabPBhYtl3bQQPJ",
	"yqZq1vY560DDj4FpTPrkSjWMspxL+US9X3vMakWD+lhQ6uS18lFVPl+tuA3UyWyryz0YWNFQAad+aIDx",
	"54hZbqk/lFmOYqmV0KYUvKtovc0zpXnNJXrNuAYDr/TLHei/R6AvXkDdzgUph3+E/E9/Kuxyopjnk1l0",
	"V+d2XHLhs91j3xb8VdedQ25trx5m2bXp+vHxvOlLxF8JnWCvkJm4LQKKhIxcVgzm2xFGDmBgI5KM1oGc",
	"DRvKYpaLRXejYfo+/QkAAP//z5lPuycDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
